[package]
authors = ["Kazuma Kondo <kazmax7@gmail.com>"]
edition = "2018"
name = "csv_to_wav"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
wav = "1.0.0"
